import { Routes } from '@angular/router';

export const gestorContenidosRoutes: Routes = [
  { path: 'dashboard', loadComponent: () => import('./dashboard/dashboard.component').then(m => m.GcDashboardComponent), data: { title: 'Dashboard - Gestor de Contenidos' } },
  { path: 'paginas', loadComponent: () => import('./paginas/paginas.component').then(m => m.PaginasComponent), data: { title: 'Páginas' } },
  { path: 'paginas/crear', loadComponent: () => import('./paginas/pagina-form.component').then(m => m.PaginaFormComponent), data: { title: 'Crear Página' } },
  { path: 'paginas/:id/editar', loadComponent: () => import('./paginas/pagina-form.component').then(m => m.PaginaFormComponent), data: { title: 'Editar Página' } },
  { path: 'menus', loadComponent: () => import('./menus/menus.component').then(m => m.MenusComponent), data: { title: 'Menús' } },
  { path: 'menus/crear', loadComponent: () => import('./menus/menu-form.component').then(m => m.MenuFormComponent), data: { title: 'Crear Menú' } },
  { path: 'menus/:id/editar', loadComponent: () => import('./menus/menu-form.component').then(m => m.MenuFormComponent), data: { title: 'Editar Menú' } },
  { path: 'menus/builder', loadComponent: () => import('./menus/menu-builder.component').then(m => m.MenuBuilderComponent), data: { title: 'Constructor de Menú' } },
  { path: 'banners', loadComponent: () => import('./banners/banners.component').then(m => m.BannersComponent), data: { title: 'Banners' } },
  { path: 'banners/crear', loadComponent: () => import('./banners/banner-form.component').then(m => m.BannerFormComponent), data: { title: 'Crear Banner' } },
  { path: 'banners/:id/editar', loadComponent: () => import('./banners/banner-form.component').then(m => m.BannerFormComponent), data: { title: 'Editar Banner' } },
  { path: 'configuracion', loadComponent: () => import('./configuracion/configuracion-sitio.component').then(m => m.ConfiguracionSitioComponent), data: { title: 'Configuración del Sitio' } },
  { path: 'temas', loadComponent: () => import('./temas/temas.component').then(m => m.TemasComponent), data: { title: 'Temas' } },
  { path: 'temas/crear', loadComponent: () => import('./temas/tema-form.component').then(m => m.TemaFormComponent), data: { title: 'Crear Tema' } },
  { path: 'temas/:id/editar', loadComponent: () => import('./temas/tema-form.component').then(m => m.TemaFormComponent), data: { title: 'Editar Tema' } },
  { path: 'plantillas', loadComponent: () => import('./plantillas/plantillas.component').then(m => m.PlantillasComponent), data: { title: 'Plantillas' } },
  { path: 'plantillas/crear', loadComponent: () => import('./plantillas/plantilla-form.component').then(m => m.PlantillaFormComponent), data: { title: 'Crear Plantilla' } },
  { path: 'plantillas/:id', loadComponent: () => import('./plantillas/plantilla-detail.component').then(m => m.PlantillaDetailComponent), data: { title: 'Ver Plantilla' } },
  { path: 'plantillas/:id/editar', loadComponent: () => import('./plantillas/plantilla-form.component').then(m => m.PlantillaFormComponent), data: { title: 'Editar Plantilla' } },
  { path: 'componentes-reutilizables', loadComponent: () => import('./componentes-reutilizables/componentes-reutilizables.component').then(m => m.ComponentesReutilizablesComponent), data: { title: 'Componentes Reutilizables' } },
  { path: 'componentes-reutilizables/crear', loadComponent: () => import('./componentes-reutilizables/componente-form.component').then(m => m.ComponenteFormComponent), data: { title: 'Crear Componente' } },
  { path: 'componentes-reutilizables/:id/editar', loadComponent: () => import('./componentes-reutilizables/componente-form.component').then(m => m.ComponenteFormComponent), data: { title: 'Editar Componente' } },
  { path: 'noticias', loadComponent: () => import('./noticias/noticias.component').then(m => m.NoticiasComponent), data: { title: 'Noticias' } },
  { path: 'noticias/crear', loadComponent: () => import('./noticias/noticia-form.component').then(m => m.NoticiaFormComponent), data: { title: 'Crear Noticia' } },
  { path: 'noticias/:id/editar', loadComponent: () => import('./noticias/noticia-form.component').then(m => m.NoticiaFormComponent), data: { title: 'Editar Noticia' } },
  { path: 'proyectos', loadComponent: () => import('./proyectos/proyectos.component').then(m => m.ProyectosComponent), data: { title: 'Proyectos' } },
  { path: 'proyectos/crear', loadComponent: () => import('./proyectos/proyecto-form.component').then(m => m.ProyectoFormComponent), data: { title: 'Crear Proyecto' } },
  { path: 'proyectos/:id/editar', loadComponent: () => import('./proyectos/proyecto-form.component').then(m => m.ProyectoFormComponent), data: { title: 'Editar Proyecto' } },
  { path: 'testimonios', loadComponent: () => import('./testimonios/testimonios.component').then(m => m.TestimoniosComponent), data: { title: 'Testimonios' } },
  { path: 'ctas', loadComponent: () => import('./ctas/ctas.component').then(m => m.CtasComponent), data: { title: 'Llamadas a la Acción' } },
  { path: 'citas', loadComponent: () => import('./citas').then(m => m.CitasComponent), data: { title: 'Gestionar Citas' } },
  { path: 'accesos-directos', loadComponent: () => import('./accesos-directos/accesos-directos.component').then(m => m.AccesosDirectosComponent), data: { title: 'Accesos Directos' } },
  { path: 'fotos-aniversario', loadComponent: () => import('./fotos-aniversario/fotos-aniversario.component').then(m => m.FotosAniversarioComponent), data: { title: 'Fotos de Aniversario' } },
  { path: 'fotos-aniversario/configurar', loadComponent: () => import('./fotos-aniversario/fotos-aniversario-configurar.component').then(m => m.FotosAniversarioConfigurarComponent), data: { title: 'Configurar Modal Aniversario' } },
  { path: 'eventos', loadComponent: () => import('./eventos/eventos.component').then(m => m.EventosComponent), data: { title: 'Eventos' } },
  { path: 'contactos', loadComponent: () => import('./contactos/contactos.component').then(m => m.ContactosComponent), data: { title: 'Contactos' } },
  { path: 'ofertas-empleo', loadComponent: () => import('./ofertas-empleo/ofertas-empleo.component').then(m => m.OfertasEmpleoComponent), data: { title: 'Ofertas de Empleo' } },
  { path: 'ofertas-empleo/crear', loadComponent: () => import('./ofertas-empleo/oferta-form.component').then(m => m.OfertaFormComponent), data: { title: 'Crear Oferta' } },
  { path: 'ofertas-empleo/:id/editar', loadComponent: () => import('./ofertas-empleo/oferta-form.component').then(m => m.OfertaFormComponent), data: { title: 'Editar Oferta' } },
  { path: 'postulaciones', loadComponent: () => import('./postulaciones/postulaciones.component').then(m => m.PostulacionesComponent), data: { title: 'Postulaciones' } },
  { path: 'servicios', loadComponent: () => import('./servicios/servicios.component').then(m => m.ServiciosComponent), data: { title: 'Servicios' } },
  { path: 'documentos', loadComponent: () => import('./documentos/documentos.component').then(m => m.DocumentosGcComponent), data: { title: 'Documentos' } },
  { path: 'categorias', loadComponent: () => import('./categorias/categorias.component').then(m => m.CategoriasComponent), data: { title: 'Categorías' } },
  { path: 'miembros', loadComponent: () => import('./miembros/miembros.component').then(m => m.MiembrosComponent), data: { title: 'Miembros del Colegio' } },
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' }
];
